# .github/workflows/blank.yml 
name: Use GitHub Secret

on:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret
        run: |
          echo "Using secret..."
          echo "${{ secrets.MY_SECRET_TOKEN }}"
          echo "Secret is set: [${{ secrets.MY_SECRET_TOKEN != '' }}]"
